# Date regex patterns for identifying date-like columns in CSV files
# Used by utils._is_date_like and data_loader._find_column

date_patterns:
  - "\\d{4}-\\d{2}-\\d{2}"      # YYYY-MM-DD
  - "\\d{2}/\\d{2}/\\d{4}"      # DD/MM/YYYY
  - "\\d{2}-\\d{2}-\\d{4}"      # DD-MM-YYYY
  - "\\d{4}/\\d{2}/\\d{2}"      # YYYY/MM/DD
  - "^Date$"                  # Exact 'Date'
  - "^Position Date$"          # Exact 'Position Date'
  - "^Trade Date$"             # Exact 'Trade Date'
  - "^AsOfDate$"               # Exact 'AsOfDate'
  - "^Effective Date$"         # Exact 'Effective Date' 